apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: msgsplit
  name: msgsplit
spec:
  replicas: 1 ## must stay 1, msgsplit is not scalable! there is no sync between pods
  selector:
    matchLabels:
      app.kubernetes.io/name: msgsplit
  template:
    metadata:
      labels:
        app.kubernetes.io/name: msgsplit
    spec:
      containers:
      - image: ghcr.io/klml/msgsplit:main
        name: msgsplit
        ports:
        - containerPort: 8080
