apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: msgsplit
  name: msgsplit
  namespace: msgsplit
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: msgsplit
  sessionAffinity: None
  type: NodePort